if(NOT DEFINED BASH_COMPLETION_DIR)
  if(DEFINED ENV{BASH_COMPLETION_DIR})
    set(BASH_COMPLETION_DIR "$ENV{BASH_COMPLETION_DIR}")
  elseif(IS_DIRECTORY "/usr/local/etc/bash_completion.d")
    set(BASH_COMPLETION_DIR "/usr/local/etc/bash_completion.d")
  else()
    message("Couldn't find bash completion directory")
  endif()
endif()
